### ISSUE TITLE
Güncel IPTV adresleri burada

### ISSUE THREAD

**Issue by burak5445** [UzunMuhalefet/Legal-IPTV#7]
Arkadaşlar herkese merhaba bu alanda günlük güncel IPTV adresleri paylaşımı yapıyoruz ve ücretsiz herkes dizi film kanal izlesin iyi seyirler

Adres: https://t.me/KnowingEye

**Comment by UzunMuhalefet** [comment]
@burak5445 birader, defol git burada reklam barındırmıyorum, illegal iş de barındırmıyorum.
